Update grpc packages to 1.80.0

diff --git a/grpc/android-x86/PKGBUILD b/grpc/android-x86/PKGBUILD
--- a/grpc/android-x86/PKGBUILD
+++ b/grpc/android-x86/PKGBUILD
@@ -2,10 +2,10 @@ _android_arch=x86
 
 _pkgname=grpc
 pkgname=android-${_android_arch}-${_pkgname}
-_protover=33.1
+_protover=34.1
 _opencensus_proto_ver=0.4.1
-pkgver=1.76.0
-pkgrel=2
+pkgver=1.80.0
+pkgrel=1
 arch=('any')
 pkgdesc="High performance, open source, general RPC framework that puts mobile and HTTP/2 first (Android ${_android_arch})"
 url='https://grpc.io'
@@ -27,9 +27,11 @@ makedepends=(
 )
 options=(!strip !buildflags staticlibs !emptydirs)
 source=("https://github.com/grpc/grpc/archive/v$pkgver/$_pkgname-$pkgver.tar.gz"
-        "https://github.com/census-instrumentation/opencensus-proto/archive/v${_opencensus_proto_ver}/opencensus-proto-${_opencensus_proto_ver}.tar.gz")
-sha256sums=('0af37b800953130b47c075b56683ee60bdc3eda3c37fc6004193f5b569758204'
-            'e3d89f7f9ed84c9b6eee818c2e9306950519402bf803698b15c310b77ca2f0f3')
+        "https://github.com/census-instrumentation/opencensus-proto/archive/v${_opencensus_proto_ver}/opencensus-proto-${_opencensus_proto_ver}.tar.gz"
+        "protobuf-34-build-fix.patch")
+sha256sums=('38f58596277fa632064cc0719b9ece4381c8c77461cb51e9b66ca149574b7865'
+            'e3d89f7f9ed84c9b6eee818c2e9306950519402bf803698b15c310b77ca2f0f3'
+            '2c126e40c54bdc88ab57fad12cbd860fc999aceb0e2787263edcbf024097ecec')
 
 prepare() {
   cd ${_pkgname}-${pkgver}
@@ -41,11 +43,20 @@ prepare() {
 
   rm -rf third_party/opencensus-proto
   mv "${srcdir}"/opencensus-proto-${_opencensus_proto_ver} third_party/opencensus-proto
+
+  patch -p1 -i "$srcdir/protobuf-34-build-fix.patch"
 }
 
 build() {
   export ANDROID_MINIMUM_PLATFORM=24
   source android-env ${_android_arch}
+
+  # Workaround for protobuf 34.0+ until https://github.com/grpc/grpc/issues/41755 has been fixed.
+  if [[ "$(pacman -Q android-$_android_arch-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protover" ]]; then
+    echo 'error: protobuf version mismatch, please update $_protover in the PKGBUILD' >&2
+    exit 1
+  fi
+  export CXXFLAGS+=" -isystem${srcdir}/protobuf-${_protobuf_ver}/src"
 
   local flags=(
     -DCMAKE_POLICY_VERSION_MINIMUM=3.5
diff --git a/grpc/mingw-w64/PKGBUILD b/grpc/mingw-w64/PKGBUILD
--- a/grpc/mingw-w64/PKGBUILD
+++ b/grpc/mingw-w64/PKGBUILD
@@ -1,9 +1,9 @@
 pkgname=mingw-w64-grpc
 _pkgname=grpc
-_protover=33.1
+_protover=34.1
 _opencensus_proto_ver=0.4.1
-pkgver=1.76.0
-pkgrel=2
+pkgver=1.80.0
+pkgrel=1
 pkgdesc="High performance, open source, general RPC framework that puts mobile and HTTP/2 first (mingw-w64)"
 arch=('any')
 url='https://grpc.io'
@@ -15,12 +15,14 @@ source=("https://github.com/grpc/grpc/archive/v$pkgver/$_pkgname-$pkgver.tar.gz"
         "https://github.com/census-instrumentation/opencensus-proto/archive/v${_opencensus_proto_ver}/opencensus-proto-${_opencensus_proto_ver}.tar.gz"
         001-fix-building-shared-libraries-with-clang.patch
         002-fix-building-python-module.patch
-        003-fix-build-shared-libs-on-mingw.patch)
-sha256sums=('0af37b800953130b47c075b56683ee60bdc3eda3c37fc6004193f5b569758204'
+        003-fix-build-shared-libs-on-mingw.patch
+        protobuf-34-build-fix.patch)
+sha256sums=('38f58596277fa632064cc0719b9ece4381c8c77461cb51e9b66ca149574b7865'
             'e3d89f7f9ed84c9b6eee818c2e9306950519402bf803698b15c310b77ca2f0f3'
             'cf4064ad294bbddf15ac0611a4920dfa133a54ccaebbf813ed4faef6b20d142b'
             'c08e9a6a4dd569155452660825c8b42a06bbc6eb1e924af98796b138e6698e93'
-            'd1b8334fbd97c833f37f03f222bd443a77772409586c1324cb5bb1b5d85037b3')
+            'd1b8334fbd97c833f37f03f222bd443a77772409586c1324cb5bb1b5d85037b3'
+            '2c126e40c54bdc88ab57fad12cbd860fc999aceb0e2787263edcbf024097ecec')
 
 _architectures="i686-w64-mingw32 x86_64-w64-mingw32"
 
@@ -38,6 +40,8 @@ prepare() {
   patch -p1 -i ../001-fix-building-shared-libraries-with-clang.patch
   patch -p1 -i ../002-fix-building-python-module.patch
   patch -p1 -i ../003-fix-build-shared-libs-on-mingw.patch
+
+  patch -p1 -i "$srcdir/protobuf-34-build-fix.patch"
 }
 
 build() {
@@ -52,6 +56,13 @@ build() {
   export CXXFLAGS+=" -DSTRSAFE_NO_DEPRECATE"
 
   export CXXFLAGS+=" -DNDEBUG -D_WIN32_WINNT=0x600 -Wno-attributes -Wno-deprecated-declarations -Wno-return-type -Wno-non-virtual-dtor"
+
+  # Workaround for protobuf 34.0+ until https://github.com/grpc/grpc/issues/41755 has been fixed.
+  if [[ "$(pacman -Q mingw-w64-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protover" ]]; then
+    echo 'error: protobuf version mismatch, please update $_protover in the PKGBUILD' >&2
+    exit 1
+  fi
+  export CXXFLAGS+=" -isystem${srcdir}/protobuf-${_protobuf_ver}/src"
 
   local flags=(
     -DCMAKE_POLICY_VERSION_MINIMUM=3.5
diff --git a/grpc/static-compat/PKGBUILD b/grpc/static-compat/PKGBUILD
--- a/grpc/static-compat/PKGBUILD
+++ b/grpc/static-compat/PKGBUILD
@@ -1,9 +1,9 @@
 _pkgname=grpc
 pkgname=static-compat-$_pkgname
-pkgver=1.76.0
+pkgver=1.80.0
 _gtestver=2dd1c131950043a8ad5ab0d2dda0e0970596586a
-_protover=33.1
-pkgrel=2
+_protover=34.1
+pkgrel=1
 pkgdesc="High performance, open source, general RPC framework that puts mobile and HTTP/2 first"
 arch=('x86_64')
 url='https://grpc.io'
@@ -21,14 +21,18 @@ makedepends=(
 )
 source=("https://github.com/grpc/grpc/archive/v$pkgver/$_pkgname-$pkgver.tar.gz"
         "https://github.com/google/googletest/archive/$_gtestver/googletest-$_gtestver.tar.gz"
-        "https://github.com/protocolbuffers/protobuf/archive/v$_protover/protobuf-$_protover.tar.gz")
-sha256sums=('0af37b800953130b47c075b56683ee60bdc3eda3c37fc6004193f5b569758204'
+        "https://github.com/protocolbuffers/protobuf/archive/v$_protover/protobuf-$_protover.tar.gz"
+        "protobuf-34-build-fix.patch")
+sha256sums=('38f58596277fa632064cc0719b9ece4381c8c77461cb51e9b66ca149574b7865'
             '31bf78bd91b96dd5e24fab3bb1d7f3f7453ccbaceec9afb86d6e4816a15ab109'
-            '0c98bb704ceb4e68c92f93907951ca3c36130bc73f87264e8c0771a80362ac97')
+            'a83103b7ed3afaeedee9a212c8f65825444f58144f5e075b73c83f2b4ff27b62'
+            '2c126e40c54bdc88ab57fad12cbd860fc999aceb0e2787263edcbf024097ecec')
 
 prepare() {
   source static-compat-environment
   cd "$srcdir/$_pkgname-$pkgver"
+
+  patch -p1 -i "$srcdir/protobuf-34-build-fix.patch"
 
   ln -sf "$srcdir/googletest-$_gtestver/"{googlemock,googletest} \
     third_party/googletest
@@ -54,6 +58,14 @@ prepare() {
 build() {
   source static-compat-environment
   cd "$srcdir/$_pkgname-$pkgver"
+
+  # Workaround for protobuf 34.0+ until https://github.com/grpc/grpc/issues/41755 has been fixed.
+  if [[ "$(pacman -Q static-compat-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protover" ]]; then
+    echo 'error: protobuf version mismatch, please update $_protover in the PKGBUILD' >&2
+    exit 1
+  fi
+  export CXXFLAGS+=" -isystem${srcdir}/protobuf-${_protobuf_ver}/src"
+
   static-compat-cmake -Bbuild \
     -DCMAKE_BUILD_TYPE=None \
     -DCMAKE_CXX_FLAGS="${CXXFLAGS} -DNDEBUG -Wno-attributes -Wno-deprecated-declarations -Wno-return-type -Wno-non-virtual-dtor" \
