Update protobuf/grpc packages

diff --git a/grpc/android-x86-64/PKGBUILD b/grpc/android-x86-64/PKGBUILD
--- a/grpc/android-x86-64/PKGBUILD
+++ b/grpc/android-x86-64/PKGBUILD
@@ -2,9 +2,9 @@ _android_arch=x86-64
 
 _pkgname=grpc
 pkgname=android-${_android_arch}-${_pkgname}
-_protover=36.0
+_protobuf_ver=36.1
 _opencensus_proto_ver=0.4.1
-pkgver=1.83.0
+pkgver=1.84.0
 pkgrel=1
 arch=('any')
 pkgdesc="High performance, open source, general RPC framework that puts mobile and HTTP/2 first (Android ${_android_arch})"
@@ -24,23 +24,45 @@ makedepends=(
   protobuf
   grpc
   ninja
+  git
 )
 options=(!strip !buildflags staticlibs !emptydirs)
-source=("https://github.com/grpc/grpc/archive/v$pkgver/$_pkgname-$pkgver.tar.gz"
-        "https://github.com/census-instrumentation/opencensus-proto/archive/v${_opencensus_proto_ver}/opencensus-proto-${_opencensus_proto_ver}.tar.gz")
-sha256sums=('90d453393a9d41215df546103b10b33b9566df79cdf6f49dc67f6c4d044d090d'
-            'e3d89f7f9ed84c9b6eee818c2e9306950519402bf803698b15c310b77ca2f0f3')
+source=(
+    "${_pkgname}::git+https://github.com/grpc/grpc.git#tag=v$pkgver"
+    "${_pkgname}-grpc-proto::git+https://github.com/grpc/grpc-proto.git"
+    "${_pkgname}-googletest::git+https://github.com/google/googletest.git"
+    "https://github.com/protocolbuffers/protobuf/archive/v${_protobuf_ver}/protobuf-${_protobuf_ver}.tar.gz")
+sha256sums=('1c63b6bb0b846345491c00e00db11694a78a9e61f24f580252fa2e1ffbad056f'
+            'SKIP'
+            'SKIP'
+            '7a7baff8207a57f3fe5c233d432a09eba67bdfb55a3145839d0817cae8e807a4')
 
 prepare() {
-  cd ${_pkgname}-${pkgver}
+  cd ${_pkgname}
 
-  if ! pkgconf protobuf --exact-version=$_protover.0; then
+  if ! pkgconf protobuf --exact-version=$_protobuf_ver.0; then
     echo "protobuf version mismatch"
     exit 1
   fi
 
-  rm -rf third_party/opencensus-proto
-  mv "${srcdir}"/opencensus-proto-${_opencensus_proto_ver} third_party/opencensus-proto
+  git submodule init
+
+  git config submodule."third_party/googletest".url "${srcdir}/${_pkgname}"-googletest
+  git config submodule."third_party/grpc-proto".url "${srcdir}/${_pkgname}"-grpc-proto
+  git -c protocol.file.allow=always submodule update --init -- third_party/grpc-proto third_party/googletest
+
+  # CMake only downloads third party depends when folder does not exist
+  rmdir third_party/{cel-spec,envoy-api,xds,googleapis,protoc-gen-validate}
+
+  # use system protobuf for grpcio_tools
+  sed -r -i \
+      -e '/^CC_FILES=\[/,/\]/{/^CC_FILES=\[/n;/\]/!d;}' \
+      -e '/^CC_INCLUDES=\[/,/\]/{/^CC_INCLUDES=\[/n;/\]/!d;}' \
+      -e "s@^(PROTO_INCLUDE=')[^']+'@\1/usr/include'@" \
+      -e "s@^(\s*').*/(google/protobuf/.*\.proto',?)\$@\1\2@" \
+      -e '/^PROTOBUF_SUBMODULE_VERSION=/d' \
+      tools/distrib/python/grpcio_tools/protoc_lib_deps.py
+  ln -s ../../../.. tools/distrib/python/grpcio_tools/grpc_root
 }
 
 build() {
@@ -48,14 +70,13 @@ build() {
   source android-env ${_android_arch}
 
   # Workaround for protobuf 34.0+ until https://github.com/grpc/grpc/issues/41755 has been fixed.
-  if [[ "$(pacman -Q android-$_android_arch-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protover" ]]; then
-    echo 'error: protobuf version mismatch, please update $_protover in the PKGBUILD' >&2
+  if [[ "$(pacman -Q android-$_android_arch-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protobuf_ver" ]]; then
+    echo 'error: protobuf version mismatch, please update $_protobuf_ver in the PKGBUILD' >&2
     exit 1
   fi
   export CXXFLAGS+=" -isystem${srcdir}/protobuf-${_protobuf_ver}/src"
 
   local flags=(
-    -DCMAKE_POLICY_VERSION_MINIMUM=3.5
     -DCMAKE_DLL_NAME_WITH_SOVERSION=ON
     -DgRPC_INSTALL=ON
     -DCMAKE_SKIP_RPATH=ON
@@ -89,7 +110,7 @@ build() {
   )
 
   android-${_android_arch}-cmake \
-    -S ${_pkgname}-${pkgver} \
+    -S ${_pkgname} \
     -B build-static \
     -D BUILD_SHARED_LIBS=OFF \
     -Dc-ares_LIBRARY="${ANDROID_PREFIX_LIB}/libcares.a" \
@@ -100,7 +121,7 @@ build() {
 
   # disabled, see https://github.com/grpc/grpc/issues/36896
   #android-${_android_arch}-cmake \
-  #  -S ${_pkgname}-${pkgver} \
+  #  -S ${_pkgname}
   #  -B build-shared \
   #  -D BUILD_SHARED_LIBS=ON \
   #  -Dc-ares_LIBRARY="${ANDROID_PREFIX_LIB}/libcares.so" \
diff --git a/grpc/mingw-w64/PKGBUILD b/grpc/mingw-w64/PKGBUILD
--- a/grpc/mingw-w64/PKGBUILD
+++ b/grpc/mingw-w64/PKGBUILD
@@ -1,47 +1,67 @@
 pkgname=mingw-w64-grpc
 _pkgname=grpc
-_protover=36.0
-_opencensus_proto_ver=0.4.1
-pkgver=1.83.0
+_protobuf_ver=36.1
+pkgver=1.84.0
 pkgrel=1
 pkgdesc="High performance, open source, general RPC framework that puts mobile and HTTP/2 first (mingw-w64)"
 arch=('any')
 url='https://grpc.io'
 license=('Apache-2.0')
 depends=(mingw-w64-zlib mingw-w64-abseil-cpp mingw-w64-c-ares mingw-w64-re2 mingw-w64-protobuf mingw-w64-openssl)
-makedepends=(mingw-w64-cmake-static protobuf grpc ninja)
+makedepends=(mingw-w64-cmake-static protobuf grpc ninja git)
 options=(!strip !buildflags staticlibs)
-source=("https://github.com/grpc/grpc/archive/v$pkgver/$_pkgname-$pkgver.tar.gz"
-        "https://github.com/census-instrumentation/opencensus-proto/archive/v${_opencensus_proto_ver}/opencensus-proto-${_opencensus_proto_ver}.tar.gz"
-        001-fix-building-shared-libraries-with-clang.patch
-        002-fix-building-python-module.patch
-        003-fix-build-shared-libs-on-mingw.patch)
-sha256sums=('90d453393a9d41215df546103b10b33b9566df79cdf6f49dc67f6c4d044d090d'
-            'e3d89f7f9ed84c9b6eee818c2e9306950519402bf803698b15c310b77ca2f0f3'
-            'cf4064ad294bbddf15ac0611a4920dfa133a54ccaebbf813ed4faef6b20d142b'
-            'c08e9a6a4dd569155452660825c8b42a06bbc6eb1e924af98796b138e6698e93'
-            'd1b8334fbd97c833f37f03f222bd443a77772409586c1324cb5bb1b5d85037b3')
+source=(
+    "${_pkgname}::git+https://github.com/grpc/grpc.git#tag=v$pkgver"
+    "${_pkgname}-grpc-proto::git+https://github.com/grpc/grpc-proto.git"
+    "${_pkgname}-googletest::git+https://github.com/google/googletest.git"
+    "https://github.com/protocolbuffers/protobuf/archive/v${_protobuf_ver}/protobuf-${_protobuf_ver}.tar.gz"
+    0001-Fix-building-shared-libraries-with-clang.patch
+    0002-Fix-building-Python-module.patch
+    0003-Fix-building-shared-libraries-for-mingw-w64.patch)
+sha256sums=('1c63b6bb0b846345491c00e00db11694a78a9e61f24f580252fa2e1ffbad056f'
+            'SKIP'
+            'SKIP'
+            '7a7baff8207a57f3fe5c233d432a09eba67bdfb55a3145839d0817cae8e807a4'
+            '5a4eda23866a8cb661426a941d58ad7dc5d5bec2e0333fb4633475193cb25ada'
+            '0911e1de0a6b399f167ff22cf5d08694f3d4a761c99ec1cd75c9bd457c4c1d5a'
+            '1a1badabb6ae147a6f217b1dfed0531d55e292be0a1b5d4354ad76696ce73f66')
 
 _architectures="i686-w64-mingw32 x86_64-w64-mingw32"
 
 prepare() {
-  cd ${_pkgname}-${pkgver}
+  cd ${_pkgname}
 
-  if ! pkgconf protobuf --exact-version=$_protover.0; then
+  if ! pkgconf protobuf --exact-version=$_protobuf_ver.0; then
     echo "protobuf version mismatch"
     exit 1
   fi
 
-  rm -rf third_party/opencensus-proto
-  mv "${srcdir}"/opencensus-proto-${_opencensus_proto_ver} third_party/opencensus-proto
+  git submodule init
 
-  patch -p1 -i ../001-fix-building-shared-libraries-with-clang.patch
-  patch -p1 -i ../002-fix-building-python-module.patch
-  patch -p1 -i ../003-fix-build-shared-libs-on-mingw.patch
+  git config submodule."third_party/googletest".url "${srcdir}/${_pkgname}"-googletest
+  git config submodule."third_party/grpc-proto".url "${srcdir}/${_pkgname}"-grpc-proto
+  git -c protocol.file.allow=always submodule update --init -- third_party/grpc-proto third_party/googletest
+
+  # CMake only downloads third party depends when folder does not exist
+  rmdir third_party/{cel-spec,envoy-api,xds,googleapis,protoc-gen-validate}
+
+  # use system protobuf for grpcio_tools
+  sed -r -i \
+      -e '/^CC_FILES=\[/,/\]/{/^CC_FILES=\[/n;/\]/!d;}' \
+      -e '/^CC_INCLUDES=\[/,/\]/{/^CC_INCLUDES=\[/n;/\]/!d;}' \
+      -e "s@^(PROTO_INCLUDE=')[^']+'@\1/usr/include'@" \
+      -e "s@^(\s*').*/(google/protobuf/.*\.proto',?)\$@\1\2@" \
+      -e '/^PROTOBUF_SUBMODULE_VERSION=/d' \
+      tools/distrib/python/grpcio_tools/protoc_lib_deps.py
+  ln -s ../../../.. tools/distrib/python/grpcio_tools/grpc_root
+
+  patch -p1 -i ../0001-Fix-building-shared-libraries-with-clang.patch
+  patch -p1 -i ../0002-Fix-building-Python-module.patch
+  patch -p1 -i ../0003-Fix-building-shared-libraries-for-mingw-w64.patch
 }
 
 build() {
-  cd ${_pkgname}-${pkgver}
+  cd ${_pkgname}
 
   # remove __USE_MINGW_ANSI_STDIO=1 define, it breaks grpc string handling for
   # cases like 'gpr_log(GPR_DEBUG, "Failed to free %" PRIuPTR ...'
@@ -54,14 +74,13 @@ build() {
   export CXXFLAGS+=" -DNDEBUG -D_WIN32_WINNT=0x600 -Wno-attributes -Wno-deprecated-declarations -Wno-return-type -Wno-non-virtual-dtor"
 
   # Workaround for protobuf 34.0+ until https://github.com/grpc/grpc/issues/41755 has been fixed.
-  if [[ "$(pacman -Q mingw-w64-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protover" ]]; then
-    echo 'error: protobuf version mismatch, please update $_protover in the PKGBUILD' >&2
+  if [[ "$(pacman -Q mingw-w64-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protobuf_ver" ]]; then
+    echo 'error: protobuf version mismatch, please update $_protobuf_ver in the PKGBUILD' >&2
     exit 1
   fi
   export CXXFLAGS+=" -isystem${srcdir}/protobuf-${_protobuf_ver}/src"
 
   local flags=(
-    -DCMAKE_POLICY_VERSION_MINIMUM=3.5
     -DCMAKE_DLL_NAME_WITH_SOVERSION=ON
     -DgRPC_INSTALL=ON
     -DCMAKE_SKIP_RPATH=ON
@@ -104,7 +123,7 @@ build() {
 }
 
 package() {
-  cd ${_pkgname}-${pkgver}
+  cd ${_pkgname}
   for _arch in ${_architectures}; do
     DESTDIR=$pkgdir cmake --install build-${_arch}
     DESTDIR=$pkgdir cmake --install build-static-${_arch}
diff --git a/grpc/static-compat/PKGBUILD b/grpc/static-compat/PKGBUILD
--- a/grpc/static-compat/PKGBUILD
+++ b/grpc/static-compat/PKGBUILD
@@ -1,8 +1,7 @@
 _pkgname=grpc
 pkgname=static-compat-$_pkgname
-pkgver=1.83.0
-_gtestver=2dd1c131950043a8ad5ab0d2dda0e0970596586a
-_protover=36.0
+pkgver=1.84.0
+_protobuf_ver=36.1
 pkgrel=1
 pkgdesc="High performance, open source, general RPC framework that puts mobile and HTTP/2 first"
 arch=('x86_64')
@@ -18,50 +17,54 @@ depends=(
 makedepends=(
   'static-compat-cmake'
   'ninja'
+  'git'
 )
-source=("https://github.com/grpc/grpc/archive/v$pkgver/$_pkgname-$pkgver.tar.gz"
-        "https://github.com/google/googletest/archive/$_gtestver/googletest-$_gtestver.tar.gz"
-        "https://github.com/protocolbuffers/protobuf/archive/v$_protover/protobuf-$_protover.tar.gz"
-        "https://patch-diff.githubusercontent.com/raw/grpc/grpc/pull/41932.patch")
-sha256sums=('90d453393a9d41215df546103b10b33b9566df79cdf6f49dc67f6c4d044d090d'
-            '31bf78bd91b96dd5e24fab3bb1d7f3f7453ccbaceec9afb86d6e4816a15ab109'
-            'd120933b88a2857c1b5fb6dafe387cca1b96762c2263cb53d945dcae34e88a3f'
-            '2c04e8acc26fda958c7ce36f256e867a941a9f9be7de9a3f8bebc832fd12182a')
+source=(
+    "${_pkgname}::git+https://github.com/grpc/grpc.git#tag=v$pkgver"
+    "${_pkgname}-grpc-proto::git+https://github.com/grpc/grpc-proto.git"
+    "${_pkgname}-googletest::git+https://github.com/google/googletest.git"
+    "https://github.com/protocolbuffers/protobuf/archive/v${_protobuf_ver}/protobuf-${_protobuf_ver}.tar.gz")
+sha256sums=('1c63b6bb0b846345491c00e00db11694a78a9e61f24f580252fa2e1ffbad056f'
+            'SKIP'
+            'SKIP'
+            '7a7baff8207a57f3fe5c233d432a09eba67bdfb55a3145839d0817cae8e807a4')
 
 prepare() {
   source static-compat-environment
-  cd "$srcdir/$_pkgname-$pkgver"
+  cd "$srcdir/$_pkgname"
 
-  patch -p1 -i "$srcdir/41932.patch" # OpenSSL 4 support
+  if ! pkgconf protobuf --exact-version=$_protobuf_ver.0; then
+    echo "protobuf version mismatch"
+    exit 1
+  fi
 
-  ln -sf "$srcdir/googletest-$_gtestver/"{googlemock,googletest} \
-    third_party/googletest
+  git submodule init
+
+  git config submodule."third_party/googletest".url "${srcdir}/${_pkgname}"-googletest
+  git config submodule."third_party/grpc-proto".url "${srcdir}/${_pkgname}"-grpc-proto
+  git -c protocol.file.allow=always submodule update --init -- third_party/grpc-proto third_party/googletest
 
   # CMake only downloads third party depends when folder does not exist
-  rmdir third_party/{envoy-api,xds,googleapis,protoc-gen-validate}
+  rmdir third_party/{cel-spec,envoy-api,xds,googleapis,protoc-gen-validate}
 
   # use system protobuf for grpcio_tools
   sed -r -i \
       -e '/^CC_FILES=\[/,/\]/{/^CC_FILES=\[/n;/\]/!d;}' \
       -e '/^CC_INCLUDES=\[/,/\]/{/^CC_INCLUDES=\[/n;/\]/!d;}' \
       -e "s@^(PROTO_INCLUDE=')[^']+'@\1/usr/include'@" \
+      -e "s@^(\s*').*/(google/protobuf/.*\.proto',?)\$@\1\2@" \
       -e '/^PROTOBUF_SUBMODULE_VERSION=/d' \
       tools/distrib/python/grpcio_tools/protoc_lib_deps.py
   ln -s ../../../.. tools/distrib/python/grpcio_tools/grpc_root
-
-  if ! pkgconf protobuf --exact-version=$_protover.0; then
-    echo "protobuf version mismatch"
-    exit 1
-  fi
 }
 
 build() {
   source static-compat-environment
-  cd "$srcdir/$_pkgname-$pkgver"
+  cd "$srcdir/$_pkgname"
 
   # Workaround for protobuf 34.0+ until https://github.com/grpc/grpc/issues/41755 has been fixed.
-  if [[ "$(pacman -Q static-compat-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protover" ]]; then
-    echo 'error: protobuf version mismatch, please update $_protover in the PKGBUILD' >&2
+  if [[ "$(pacman -Q static-compat-protobuf | grep -Po '(?<= )[0-9.]+(?=-)')" != "$_protobuf_ver" ]]; then
+    echo 'error: protobuf version mismatch, please update $_protobuf_ver in the PKGBUILD' >&2
     exit 1
   fi
   export CXXFLAGS+=" -isystem${srcdir}/protobuf-${_protobuf_ver}/src"
@@ -98,7 +101,7 @@ build() {
 }
 
 package() {
-  cd "$srcdir/$_pkgname-$pkgver/build"
+  cd "$srcdir/$_pkgname/build"
   DESTDIR="$pkgdir" cmake --install .
   install -Dm644 ../LICENSE "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
 }
